---
name: Branch Descendant
description: Ensure closest MST parent branch is master.
outputs:
  valid:
    description: "If the PR is valid."
    value: ${{ steps.actions-branch-descendant.outputs.valid }}
  PR-string:
    description: "If the PR is valid."
    value: ${{ steps.actions-branch-descendant.outputs.PR-string }}
  closest-MST-parent:
    description: "If the PR is valid."
    value: ${{ steps.actions-branch-descendant.outputs.closest-MST-parent }}
  stdoutput:
    description: "If the PR is valid."
    value: ${{ steps.actions-branch-descendant.outputs.stdout }}
runs:
  using: "composite"
  steps:
    - id: actions-branch-descendant
      run: ./actions-branch-descendant.sh
      shell: bash