---
name: Branch Descendant
description: Ensure closest MST parent branch is master.
inputs:
  develop_branch:
    description: "Name of designated development branch"
    required: true
    default: "develop"
  test_branch:
    description: "Name of designated test branch"
    required: true
    default: "test"
  production_branch:
    description: "Name of designated production branch"
    required: true
    default: "master"
outputs:
  valid:
    description: "If the branch's closest MST parent branch is Master."
    value: ${{ steps.actions-branch-descendant.outputs.valid }}
  PR-string:
    description: "String indicating whether or not PR is good to go."
    value: ${{ steps.actions-branch-descendant.outputs.PR-string }}
  closest-MST-parent:
    description: "The closest MST parent. Either Master, Develop, or Test."
    value: ${{ steps.actions-branch-descendant.outputs.closest-MST-parent }}
runs:
  using: "composite"
  steps:
    - id: actions-branch-descendant
      env:
        DEVELOP_BRANCH_NAME: ${{ inputs.develop_branch }}
        TEST_BRANCH_NAME: ${{ inputs.test_branch }}
        PRODUCTION_BRANCH_NAME: ${{ inputs.production_branch }}
      run: ${{ github.action_path }}/actions-branch-descendant.sh
      shell: bash
