name: Branch Descendant Validation
on:
  pull_request:
    branches:
      - develop
      - test
      - master
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run colpal/actions-branch-descendant
        id: actions-branch-descendant
        continue-on-error: true
        uses: colpal/actions-branch-descendant@master

      - name: Output Vars
        env:
          VALID: "${{ steps.actions-branch-descendant.outputs.valid }}"
          PR_STRING: "${{ steps.actions-branch-descendant.outputs.PR-string }}"
          PARENT: "${{ steps.actions-branch-descendant.outputs.closest-MST-parent }}"
        run: |
          echo Parent is valid? $VALID
          echo Closest MST branch is: $PARENT
          echo $PR_STRING
      - name: Update Pull Request
        uses: actions/github-script@0.9.0
        env:
          VALID: "${{ steps.actions-branch-descendant.outputs.valid }}"
          PR_STRING: "${{ steps.actions-branch-descendant.outputs.PR-string }}"
          PARENT: "${{ steps.actions-branch-descendant.outputs.closest-MST-parent }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `### ${ process.env.PR_STRING }
            #### Closest MST parent branch needs to be: \`Master\`.
            #### Closest MST parent branch is: \`${ process.env.PARENT }\`.
            #### Closest MST parent is Master? \`${ process.env.VALID }\`.
            #### Read more about MST here: https://github.com/colpal/MST-branching.
            ### ${ process.env.PR_STRING }`;
              
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
