---
name: Test

'on': push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run colpal/actions-branch-descendant
        id: actions-branch-descendant
        continue-on-error: true
        uses: colpal/actions-branch-descendant

      - name: Output Vars
        env:
          VALID: "${{ steps.actions-branch-descendant.outputs.valid }}"
          PR-STRING: "${{ steps.actions-branch-descendant.outputs.PR-string }}"
          PARENT: "${{ steps.actions-branch-descendant.outputs.closest-MST-parent }}"
        run: |
          echo Parent is valid? $VALID
          echo Closest MST branch is: $PARENT
          echo $PR-STRING