---
name: Test

'on': push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run colpal/actions-branch-descendant
        id: actions-branch-descendant
        continue-on-error: true
        uses: ./

      - name: Output Vars
        env:
          VALID: "${{ steps.actions-branch-descendant.outputs.valid }}"
          PR-STRING: "${{ steps.actions-branch-descendant.outputs.PR-string }}"
          PARENT: "${{ steps.actions-branch-descendant.outputs.closest-MST-parent }}"
          STDOUTPUT: "${{ steps.actions-branch-descendant.outputs.stdout }}"

        run: |
          echo "Parent is valid? ${process.env.VALID}"
          echo "Closest MST branch is: ${process.env.PARENT}
          echo ${process.env.PR-STRING}
          echo ${process.env.STDOUTPUT}