---
name: Test

'on': push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run colpal/actions-branch-descendant
        id: actions-branch-descendant
        continue-on-error: true
        uses: ./

      - name: Output Vars
        run: |
          echo "Parent is valid? ${{ steps.actions-branch-descendant.outputs.valid }}"
          echo "Closest MST branch is: ${{ steps.actions-branch-descendant.outputs.closest-MST-parent }}"
          echo "${{ steps.actions-branch-descendant.outputs.PR-string }}"